Put the --with-tclsh option back in.
PR:
Obtained from:
Submitted by:
Reviewed by:

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -26219,6 +26219,23 @@ _ACEOF
 # Add WISH as well if this is a Tk extension.
 #--------------------------------------------------------------------
 
+#
+# allow them to override the tclsh we think we found
+#
+if test x"${with_tclsh}" != x ; then
+    echo "$as_me:$LINENO: checking for tclsh" >&5
+echo $ECHO_N "checking for tclsh... $ECHO_C" >&6
+    if test -f "${with_tclsh}" ; then
+        TCLSH_PROG=${with_tclsh}
+        echo "$as_me:$LINENO: result: manually set by --with-tclsh=$TCLSH_PROG" >&5
+echo "${ECHO_T}manually set by --with-tclsh=$TCLSH_PROG" >&6
+    else
+        { { echo "$as_me:$LINENO: error: No tclsh at place specified by --with-tclsh (${with_tclsh})" >&5
+echo "$as_me: error: No tclsh at place specified by --with-tclsh (${with_tclsh})" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+
+else
 
     echo "$as_me:$LINENO: checking for tclsh" >&5
 echo $ECHO_N "checking for tclsh... $ECHO_C" >&6
@@ -26259,6 +26276,8 @@ echo "$as_me: error: No tclsh found in PATH:  $search_path" >&2;}
    { (exit 1); exit 1; }; }
     fi
 
+
+fi
 
 #TEA_PROG_WISH
 
